<a href="https://colab.research.google.com/github/LeDongAnhKiet/Data_Analytics_/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
a = np.array([1,5,6,7,8])
print(a,'\n')
a = np.append(a, 9) # Thêm 1 phần tử vào cuối
print(a,'\n')
a = np.insert(a, 1, [2,3,4])  # Chèn các phần tử vào vị trí thứ 1
print(a,'\n')
a = np.delete(a, [0, 3])  # Xóa vị trí thứ 0 và 3
print(a,'\n')
b = a.copy() # Sao chép giá trị vào b
print(b,'\n')

[1 5 6 7 8] 

[1 5 6 7 8 9] 

[1 2 3 4 5 6 7 8 9] 

[2 3 5 6 7 8 9] 

[2 3 5 6 7 8 9] 



In [13]:
a = np.array([[1,2],[1,2]])
b = np.array([[3,4],[3,4]])

# Ghép 2 mảng thành 1 mảng, giữ các chiều
arr = np.concatenate((a, b))
print(arr,'\n')

# Ghép 2 mảng thành 1 mảng, số chiều theo số mảng được ghép
arr = np.concatenate((a, b), axis=1)
print(arr,'\n')

[[1 2]
 [1 2]
 [3 4]
 [3 4]] 

[[1 2 3 4]
 [1 2 3 4]] 



In [12]:
# Xếp 2 mảng thành dọc
arr = np.vstack((a, b))
print(arr,'\n')

# Ghép 2 thành ngang
arr = np.hstack((a, b))
print(arr,'\n')

[[1 2]
 [1 2]
 [3 4]
 [3 4]] 

[[1 2 3 4]
 [1 2 3 4]] 



In [17]:
a = np.array([1,2,3,4,5,1,2,3,4,6,1,2,6])
print(np.unique(a),'\n') # Lọc giá trị trùng
b, dem = np.unique(a, return_counts=True)
print(b,'\n',dem) # Lọc và đếm giá trị trùng

[1 2 3 4 5 6] 

[1 2 3 4 5 6] 
 [3 3 2 2 1 2]


In [20]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])

print(np.intersect1d(a,b))  # Lấy phần tử giống nhau
print(np.union1d(a,b))  # Lọc phần tử trùng
print(np.setdiff1d(a,b))  # Lọc phần tử của a không trùng với b
print(np.setxor1d(a,b)) # Lọc phần tử không trùng

[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[1 2 6 7]
