<a href="https://colab.research.google.com/github/LeDongAnhKiet/Data_Analytics_/blob/main/Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Nơi import các thư viện hỗ trợ DA
import numpy as np

In [5]:
# Tạo 1 mảng
arr = np.array([1,2,3])
print(arr, '\n')  # In tất cả phần tử trong mảng
print(type(arr), '\n')  # In kiểu dữ liệu
print(arr.shape, '\n')  # In kích thước mảng

[1 2 3] 

<class 'numpy.ndarray'> 

(3,) 



In [6]:
print(arr[2],'\n') # In phần tử thứ 2 (đếm từ 0)
arr[2] = 5  # Gán giá trị mới vào phần tử thứ 2
print(arr, '\n')

3 

[1 2 5] 



In [18]:
arr = np.array([[1,2,3],[4,5,6]]) # Mảng 2 chiều
print(arr, '\n')
print(type(arr), '\n')
print(arr.shape, '\n')
print(arr.ndim, '\n') # Số chiều

[[1 2 3]
 [4 5 6]] 

<class 'numpy.ndarray'> 

(2, 3) 

2 



In [13]:
# Gán giá trị từ 0 đến 50, cách nhau 5 giá trị
arr = np.arange(0, 50, 5)
print(arr, '\n')

# Gán ngẫu nhiên giá trị
arr = np.random.rand(10)
print(arr, '\n')

# Gán chỉ giá trị 0
arr = np.zeros((3,4))
print(arr, '\n')

# Gán chỉ giá trị 1
arr = np.ones((2,3,5))
print(arr, '\n')

[ 0  5 10 15 20 25 30 35 40 45] 

[0.52814746 0.86455154 0.70004103 0.00716342 0.30312184 0.2086607
 0.85355706 0.58112619 0.27239699 0.86729712] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] 



In [16]:
arr =[1,2,3]
print(np.repeat(arr, 3), '\n')  # Lặp các phần tử 3 lần
print(np.tile(arr, 3), '\n')  # Lặp mảng 3 lần

arr = np.eye(3) # ma trận đơn vị
print(arr, '\n')

arr = np.diag([3,5,7,9]) # ma trận chéo
print(arr, '\n')

[1 1 1 2 2 2 3 3 3] 

[1 2 3 1 2 3 1 2 3] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[3 0 0 0]
 [0 5 0 0]
 [0 0 7 0]
 [0 0 0 9]] 



In [22]:
arr = np.random.rand(5,5)
print(arr,'\n')
print(np.diag(arr),'\n') # Lấy đường chéo của arr thành mảng

print(arr+10,'\n')  # Cộng tất cả phần tử lên 10
print(arr*2,'\n') # Nhân tất cả phần tử cho 2
print(arr/3,'\n') # Chia tất cả phần tử cho 3

print(np.exp(arr),'\n') # Trả về e^x
print(np.log(arr),'\n') # Trả về log^e(x)
print(np.log2(arr),'\n')  # Trả về log^2(x)
print(np.log10(arr),'\n') # Trả về log^10(x)

print(np.sin(arr),'\n') # Trả về sin(x)
print(np.cos(arr),'\n') # Trả về cos(x)
print(np.tan(arr),'\n') # Trả về (x)

[[0.68395254 0.1894508  0.19725571 0.60242751 0.37868854]
 [0.4109821  0.25036843 0.93373966 0.71347864 0.92878976]
 [0.39787846 0.14327446 0.97280032 0.42501486 0.32564173]
 [0.3881529  0.82406595 0.6627285  0.71062341 0.17985709]
 [0.3997322  0.32984358 0.63972002 0.56317661 0.99225161]] 

[0.68395254 0.25036843 0.97280032 0.71062341 0.99225161] 

[[10.68395254 10.1894508  10.19725571 10.60242751 10.37868854]
 [10.4109821  10.25036843 10.93373966 10.71347864 10.92878976]
 [10.39787846 10.14327446 10.97280032 10.42501486 10.32564173]
 [10.3881529  10.82406595 10.6627285  10.71062341 10.17985709]
 [10.3997322  10.32984358 10.63972002 10.56317661 10.99225161]] 

[[1.36790509 0.37890159 0.39451143 1.20485503 0.75737708]
 [0.82196421 0.50073685 1.86747932 1.42695729 1.85757953]
 [0.79575692 0.28654893 1.94560064 0.85002972 0.65128346]
 [0.77630579 1.64813191 1.325457   1.42124682 0.35971418]
 [0.7994644  0.65968717 1.27944003 1.12635322 1.98450322]] 

[[0.22798418 0.06315027 0.0657519  0.

In [24]:
print(np.sum(arr),'\n') # Tổng các phần tử
print(np.sum(arr, axis=0),'\n') # Tổng các cột
print(np.sum(arr, axis=1),'\n') # Tổng các dòng

print(np.min(arr),'\n') # Số nhỏ nhất
print(np.max(arr),'\n') # Số lớn nhất

13.243895413846495 

[2.2806982  1.73700323 3.40624421 3.01472104 2.80522873] 

[2.05177511 3.2373586  2.26460983 2.76542785 2.92472402] 

0.14327446488987183 

0.9922516085925149 



In [28]:
print(np.mean(arr),'\n')  # Trung bình cộng
print(np.mean(arr, axis=0),'\n')  # Trung bình cộng cột
print(np.median(arr),'\n')  # Số ở giữa mảng
print(np.median(arr, axis=1),'\n')  # Số ở giữa hàng
print(np.std(arr),'\n') # Độ lệch
print(np.var(arr),'\n') # Phương sai

print(np.sort(arr,axis=0),'\n') # Sắp xếp theo cột
print(arr.T,'\n') # Lật cột thành hàng, hàng thành cột
print(arr.flatten(),'\n') # Trả về mảng 1 chiều

0.5297558165538598 

[0.45613964 0.34740065 0.68124884 0.60294421 0.56104575] 

0.42501485813002404 

[0.37868854 0.71347864 0.39787846 0.6627285  0.56317661] 

0.2612087265224741 

0.06822999881149268 

[[0.3881529  0.14327446 0.19725571 0.42501486 0.17985709]
 [0.39787846 0.1894508  0.63972002 0.56317661 0.32564173]
 [0.3997322  0.25036843 0.6627285  0.60242751 0.37868854]
 [0.4109821  0.32984358 0.93373966 0.71062341 0.92878976]
 [0.68395254 0.82406595 0.97280032 0.71347864 0.99225161]] 

[[0.68395254 0.4109821  0.39787846 0.3881529  0.3997322 ]
 [0.1894508  0.25036843 0.14327446 0.82406595 0.32984358]
 [0.19725571 0.93373966 0.97280032 0.6627285  0.63972002]
 [0.60242751 0.71347864 0.42501486 0.71062341 0.56317661]
 [0.37868854 0.92878976 0.32564173 0.17985709 0.99225161]] 

[0.68395254 0.1894508  0.19725571 0.60242751 0.37868854 0.4109821
 0.25036843 0.93373966 0.71347864 0.92878976 0.39787846 0.14327446
 0.97280032 0.42501486 0.32564173 0.3881529  0.82406595 0.6627285
 0.71062341